# Site settings
default_locale: "ru"

title:          Техноблог Антона
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/blog"
url:            "https://chesterhow.github.io"

# Author
author:
  name:         Антон
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
