description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://antonevmenenko.github.io"

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

paginate:       5

default_language: 'en'

defaults:
- scope:
    path: 'index.html'
  values:
    permalink: ''
    language: 'en'
- scope:
    path: 'index_ru.html'
  values:
    permalink: '/ru/'
    language: 'ru'
- scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: 'en/:year-:month-:day/:title'
    language: 'en'
- scope:
    path: '_posts/ru'
    type: 'posts'
  values:
    permalink: 'ru/:year-:month-:day/:title'
    language: 'ru'
- scope:
    path: 'gallery.html'
  values:
    permalink: '/gallery/'
    language: 'en'
- scope:
    path: 'gallery_ru.html'
  values:
    permalink: '/ru/gallery/'
    language: 'ru'